/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OtherGames;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author seedh
 */
public class OddEven extends javax.swing.JFrame {
    
    String RegisterID="";
    static int score = 0;
    static int count = 1;

    //generate rendom for each question(number)
    Random r = new Random();
    int randomNum;

    /**
     * Creates new form OddEven
     */
    public OddEven() {
        initComponents();
        //first time generate random
        randomNum = r.nextInt(100);
        LblNumber.setText(String.valueOf(randomNum));
        lblDsplay.setVisible(false);
    }
    
    public void setData(String ID){
        RegisterID=ID;
    }

    public void resetGame() {
        count = 1;
        score = 0;
        LblScr.setText("00");
        randomNum = r.nextInt(100);
        LblNumber.setText(String.valueOf(randomNum));

        BtnEven.setEnabled(true);
        BtnOdd.setEnabled(true);

        lblCount.setText(count + "");
        lblDsplay.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblScr = new javax.swing.JLabel();
        LblNumber = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LblScore = new javax.swing.JLabel();
        BtnOdd = new javax.swing.JButton();
        BtnEven = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnReattempt = new javax.swing.JButton();
        lblCount = new javax.swing.JLabel();
        lblDsplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LblScr.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblScr.setForeground(new java.awt.Color(0, 153, 102));
        LblScr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblScr.setText("00");

        LblNumber.setBackground(new java.awt.Color(204, 255, 255));
        LblNumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblNumber.setForeground(new java.awt.Color(0, 102, 102));
        LblNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GUESS THE NUMBER ODD OR EVEN");

        LblScore.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblScore.setForeground(new java.awt.Color(255, 51, 51));
        LblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblScore.setText("SCORE");

        BtnOdd.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        BtnOdd.setText("ODD");
        BtnOdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOddActionPerformed(evt);
            }
        });

        BtnEven.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        BtnEven.setText("EVEN");
        BtnEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEvenActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReattempt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReattempt.setText("Re- Attempt");
        btnReattempt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReattemptActionPerformed(evt);
            }
        });

        lblCount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCount.setText("1");

        lblDsplay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDsplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDsplay.setText("desplay");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnReattempt)
                                .addGap(89, 89, 89))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblScr, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnEven, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnOdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblCount, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDsplay, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCount, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(LblNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addComponent(BtnOdd)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEven)
                        .addGap(21, 21, 21)
                        .addComponent(lblDsplay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblScr, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnReattempt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOddActionPerformed
        // TODO add your handling code here:
        //odd operation
        count = count + 1;//each buttonclick count question add 1 out of 10
        int num = Integer.parseInt(LblNumber.getText());//LblNumber is random num and convert to int for convert to odd even operation
        if (count == 10) {
            //when counter reach last question(number)
            //than it culculate for last number
            if (num % 2 != 0) {
                //number corret add score 
                score = score + 1;
                LblScr.setText(String.valueOf(score));//set value of score when answer correct
                randomNum = r.nextInt(100);//set value of score when answer correct

            } else {
                //if not add number
                randomNum = r.nextInt(100);
                LblNumber.setText(String.valueOf(randomNum));//set randomnumber

            }

            //result display on 10th question
            //JOptionPane.showMessageDialog(this, "Your Score is: " + score + "/10");
            lblDsplay.setVisible(true);
            lblDsplay.setText("Your Score is: " + score + "/10");
            //reset value after score
            BtnEven.setEnabled(false);
            BtnOdd.setEnabled(false);
        } else {
            //if number not reach 10th question (for 1 to 9)
            if (num % 2 != 0) {
                score = score + 1;
                LblScr.setText(String.valueOf(score));//set score value
                //generate random number for next question
                randomNum = r.nextInt(100);
                LblNumber.setText(String.valueOf(randomNum));

            } else {
                //if not odd than generate random for next
                randomNum = r.nextInt(100);
                LblNumber.setText(String.valueOf(randomNum));

            }
        }
        lblCount.setText(count + "");
    }//GEN-LAST:event_BtnOddActionPerformed

    private void BtnEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEvenActionPerformed
        // TODO add your handling code here:
        //change to past 
        count = count + 1;//each buttonclick count question add 1 out of 10
        int num = Integer.parseInt(LblNumber.getText());//LblNumber is random num and convert to int for convert to odd even operation
        if (count == 10) {
            //when counter reach last question(number)
            //than it culculate for last number
            if (num % 2 == 0) {
                //number corret add score 
                score = score + 1;
                LblScr.setText(String.valueOf(score));//set value of score when answer correct
                randomNum = r.nextInt(100);//set value of score when answer correct

            } else {
                //if not add number
                randomNum = r.nextInt(100);
                LblNumber.setText(String.valueOf(randomNum));//set randomnumber

            }

            //result display on 10th question
            //JOptionPane.showMessageDialog(this, "Your Score is: " + score + "/10");
            lblDsplay.setVisible(true);
            lblDsplay.setText("Your Score is: " + score + "/10");
            //reset value after score
            BtnEven.setEnabled(false);
            BtnOdd.setEnabled(false);

        } else {
            //if number not reach 10th question (for 1 to 9)
            if (num % 2 == 0) {
                score = score + 1;
                LblScr.setText(String.valueOf(score));//set score value
                //generate random number for next question
                randomNum = r.nextInt(100);
                LblNumber.setText(String.valueOf(randomNum));

            } else {
                //if not odd than generate random for next
                randomNum = r.nextInt(100);
                LblNumber.setText(String.valueOf(randomNum));

            }
        }
        lblCount.setText(count + "");
    }//GEN-LAST:event_BtnEvenActionPerformed

    private void btnReattemptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReattemptActionPerformed
        // TODO add your handling code here:
        resetGame();
    }//GEN-LAST:event_btnReattemptActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        OtherGamesMain otherGameMain = new OtherGamesMain();
        otherGameMain.Setdata(RegisterID);
        otherGameMain.show();
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OddEven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OddEven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OddEven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OddEven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OddEven().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEven;
    private javax.swing.JButton BtnOdd;
    private javax.swing.JLabel LblNumber;
    private javax.swing.JLabel LblScore;
    private javax.swing.JLabel LblScr;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReattempt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblDsplay;
    // End of variables declaration//GEN-END:variables
}
